name: mon_sirh_mobile
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.2


  # PDF Viewing
  flutter_pdfview: ^1.3.2

  # UI & Navigation
  cupertino_icons: ^1.0.8
  go_router: ^14.2.1
  flutter_screenutil: ^5.9.3

  # State Management
  provider: ^6.1.2

  # Networking & Auth
  http: ^1.2.2
  jwt_decode: ^0.3.1

  # PDF Generation
  syncfusion_flutter_pdf: ^26.2.4
  pdf: ^3.11.0

  # File Handling
  path_provider: ^2.0.15
  image_picker: ^1.1.2
  file_picker: ^8.0.6
  dio: ^5.5.0+1

  # Charts & Calendar
  fl_chart: ^0.68.0
  syncfusion_flutter_charts: ^26.2.4
  table_calendar: ^3.1.2
  syncfusion_flutter_calendar: ^26.2.4
  firebase_core: ^3.13.1
  firebase_auth: ^5.5.4
  cloud_firestore: ^5.6.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
